### ISSUE TITLE
Make the errors more explicit

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/django-setup-configuration#74]
Dimpact reported that with the following configuration:

```yaml
sites_config:
  items:
    - domain: notificaties.example.nl
      name: "Open Notificaties op Productieomgeving Example-Example"
```

They got the following error:
```
CommandError: Error while executing step `Sites configuration`: Validation error(s) occurred for the current site notificaties.example.nl.
```

The name field has a max of 50 chars, but this is not clear from the error. It would make resolving these configuration errors easier if it explicitly reported which validation error caused the problem.
