### ISSUE TITLE
Injecting secrets in yaml file

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/django-setup-configuration#78]
**Problem**

Wider context: https://github.com/maykinmedia/charts/issues/234

Currently, in our helm charts we store secrets in the Kubernetes secrets so that they come to be in the environment of the pod that runs the configuration job. We use the following syntax in the charts ([example](https://github.com/maykinmedia/charts/blob/09bfe2f88ffdf0cb8d955c7cc12835b9fb6fefaf/charts/openforms/values.yaml#L45)): `${keycloak_client_secret}`

```
oidc_db_config_enable: True
oidc_db_config_admin_auth:
  items:
  - identifier: admin-oidc
    enabled: True
    oidc_rp_client_id: openinwoner.example.nl 
    oidc_rp_client_secret: ${keycloak_client_secret}
```

Then we use envsubst to inject the secrets in the yaml, and then we run django setup configuration.

However, this is causing problems if there are `$` anywhere in the yaml. 

**Wish**

We should find a way to be able to not hardcode secrets in the yaml that is used in the helm chart and have a way to get the secrets from the environment.

**Suggestion**

Could we maybe extract the secrets from the environment during the setup configuration step? We would need to come up with a syntax that makes it possible to mark some values in the yaml as "variables" that need to be taken from the environment?

Note: we need to make sure that the snippet for OF to configure the json templates still work and that we don't interfere with the helm template syntax.

**Comment by SilviaAmAm** [comment]
Suggestion from Sergei:

Use the yaml syntax to specify which values should come from the environment. This would for example give:
```
oidc_enabled: true
oidc:
  client_secret:
     valueFrom:
        env: MY_OIDC_CLIENT_SECRET
```
Instead of now:

```
oidc_enabled: true
oidc:
  client_secret: 'supersecretvalue'
```
